version: '3'

services:
  drupal:
    image: drupal:latest # this will use the latest version of 1.13.x
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres:latest 
    environment:
      - POSTGRES_PASSWORD=aaa
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
