version: '3'

services:
  drupal:
    image: drupal:latest # this will use the latest version of 1.13.x
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    links:
      - postgres:postgres
  postgres:
    image: postgres:latest  # this will use httpd:latest
    environment:
      - POSTGRES_PASSWORD=aaa
